/*
 * Sample Password Flow OAuth2 Project
 *
 * This is an example of using OAuth2 Password Flow in a specification to describe security to your API.
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type Test struct {
	Id int  `json:"id,omitempty"`
	Questions []Question

}
type Question interface {
	
}

type OneChoiceQuestion struct {
	
}

type MultipleChoiceQuestion struct {
	
}

type WriteAnswerQuestion struct {

}

