/*
 * Sample Password Flow OAuth2 Project
 *
 * This is an example of using OAuth2 Password Flow in a specification to describe security to your API.
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type Student struct {

	Id int64 `json:"id,omitempty"`

	Name string `json:"name,omitempty"`

	LastName string `json:"lastName,omitempty"`

	FatherName string `json:"father_name,omitempty"`

	Email string `json:"email,omitempty"`

	Password string `json:"password,omitempty"`
}

