/*
 * Sample Password Flow OAuth2 Project
 *
 * This is an example of using OAuth2 Password Flow in a specification to describe security to your API.
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

import (
	"net/http"
	"strings"

	"github.com/gorilla/mux"
)

type Route struct {
	Name        string
	Method      string
	Pattern     string
	HandlerFunc http.HandlerFunc
}

type Routes []Route

func NewRouter() *mux.Router {
	router := mux.NewRouter().StrictSlash(true)
	for _, route := range routes {
		var handler http.Handler
		handler = route.HandlerFunc
		handler = authMiddleware(handler, route.Name)
		handler = Logger(handler, route.Name)

		router.
			Methods(route.Method).
			Path(route.Pattern).
			Name(route.Name).
			Handler(handler)
	}

	return router

}

func Index(w http.ResponseWriter, r *http.Request) {
	//fmt.Fprintf(w, "Hello World!")
}

var routes = Routes{
	Route{
		"Index",
		"GET",
		"/api/",
		Index,
	},

	Route{
		"AudioStudentIdGet",
		strings.ToUpper("Get"),
		"/api/audio/{studentId}",
		AudioStudentIdGet,
	},

	Route{
		"AudioStudentIdPost",
		strings.ToUpper("Post"),
		"/api/audio/{studentId}",
		AudioStudentIdPost,
	},

	Route{
		"StudentCreateWithArrayPost",
		strings.ToUpper("Post"),
		"/api/student/createWithArray",
		StudentCreateWithArrayPost,
	},

	Route{
		"StudentPost",
		strings.ToUpper("Post"),
		"/api/student",
		StudentPost,
	},

	Route{
		"StudentPut",
		strings.ToUpper("Put"),
		"/api/student",
		StudentPut,
	},

	Route{
		"StudentsDelete",
		strings.ToUpper("Delete"),
		"/api/students",
		StudentsDelete,
	},

	Route{
		"StudentsGet",
		strings.ToUpper("Get"),
		"/api/students",
		StudentsGet,
	},

	Route{
		"TestPost",
		strings.ToUpper("Post"),
		"/api/test",
		TestPost,
	},

	Route{
		"TestPut",
		strings.ToUpper("Put"),
		"/api/test",
		TestPut,
	},

	Route{
		"TeachersGet",
		strings.ToUpper("Get"),
		"/api/teachers",
		TeachersGet,
	},

	Route{
		"TeacherPost",
		strings.ToUpper("Post"),
		"/api/teacher",
		TeacherPost,
	},

	Route{
		"TeacherDelete",
		strings.ToUpper("Delete"),
		"/api/teacher",
		TeacherDelete,
	},

	Route{
		"CheckCredentialsTeacherPost",
		strings.ToUpper("Post"),
		"/api/checkCredentialsTeacher",
		CheckCredentialsTeacherPost,
	},
	Route{
		"CheckCredentialsPost",
		strings.ToUpper("Post"),
		"/api/checkCredentials",
		CheckCredentialsPost,
	},
	Route{
		"LoginPost",
		strings.ToUpper("Post"),
		"/api/login",
		LoginPost,
	},
}
