/*
 * Sample Password Flow OAuth2 Project
 *
 * This is an example of using OAuth2 Password Flow in a specification to describe security to your API.
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

import (
	"fmt"
	"net/http"
	"strings"

	"github.com/gorilla/mux"
)

type Route struct {
	Name        string
	Method      string
	Pattern     string
	HandlerFunc http.HandlerFunc
}

type Routes []Route

func NewRouter() *mux.Router {
	router := mux.NewRouter().StrictSlash(true)
	for _, route := range routes {
		var handler http.Handler
		handler = route.HandlerFunc
		handler = Logger(handler, route.Name)

		router.
			Methods(route.Method).
			Path(route.Pattern).
			Name(route.Name).
			Handler(handler)
	}

	return router
}

func Index(w http.ResponseWriter, r *http.Request) {
	fmt.Fprintf(w, "Hello World!")
}

var routes = Routes{
	Route{
		"Index",
		"GET",
		"/",
		Index,
	},

	Route{
		"AudioStudentIdGet",
		strings.ToUpper("Get"),
		"/audio/{studentId}",
		AudioStudentIdGet,
	},

	Route{
		"AudioStudentIdPost",
		strings.ToUpper("Post"),
		"/audio/{studentId}",
		AudioStudentIdPost,
	},

	Route{
		"ExampleGet",
		strings.ToUpper("Get"),
		"/example",
		ExampleGet,
	},

	Route{
		"PingGet",
		strings.ToUpper("Get"),
		"/ping",
		PingGet,
	},

	Route{
		"StudentCreateWithArrayPost",
		strings.ToUpper("Post"),
		"/student/createWithArray",
		StudentCreateWithArrayPost,
	},

	Route{
		"StudentPost",
		strings.ToUpper("Post"),
		"/student",
		StudentPost,
	},

	Route{
		"StudentPut",
		strings.ToUpper("Put"),
		"/student",
		StudentPut,
	},

	Route{
		"StudentsDelete",
		strings.ToUpper("Delete"),
		"/students",
		StudentsDelete,
	},

	Route{
		"StudentDelete",
		strings.ToUpper("Delete"),
		"/student",
		StudentDelete,
	},

	Route{
		"StudentsGet",
		strings.ToUpper("Get"),
		"/students",
		StudentsGet,
	},

	Route{
		"TestPost",
		strings.ToUpper("Post"),
		"/test",
		TestPost,
	},

	Route{
		"TestPut",
		strings.ToUpper("Put"),
		"/test",
		TestPut,
	},
}
