/*
 * Sample Password Flow OAuth2 Project
 *
 * This is an example of using OAuth2 Password Flow in a specification to describe security to your API.
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package main

import (
	sw "./go"
	"log"
	"net/http"
)

func main() {
	log.Printf("Server started")
	sw.InitDB()
	router := sw.NewRouter()

	log.Fatal(http.ListenAndServe(":8080", router))

}

// вроде все проверяй  getAllStudents воот этот метод я где-то писал вроде бы в попробуй его найти в бекапе и скопировать просто ok
// ладно похуй заново напишу там нет видимо придется ничего страшного
// ты лучше покажи щас вот как мне делать чтоб такой хуйни не было
// типа
